### ISSUE TITLE
Deconstructing a chair while sitting in it floods the server with errors

### ISSUE THREAD

**Issue by DebugOk** [DeltaV-Station/Delta-v-rebase#266]
## Description
What the fuck??

**Reproduction**
1. Sit in chair
2. Dismantle
3. Cry

**Additional context**
```
Can't resolve "Robust.Shared.GameObjects.MetaDataComponent" on entity 5690!
   at Content.Shared.Buckle.Components.BuckleComponent.BuckleComponent_AutoNetworkSystem.OnGetState(EntityUid uid, BuckleComponent component, ComponentGetState& args) in /home/runner/work/Delta-v-rebase/Delta-v-rebase/Content.Shared/Robust.Shared.CompNetworkGenerator/Robust.Shared.CompNetworkGenerator.ComponentNetworkGenerator/BuckleComponent_CompNetwork.g.cs:line 33
   at Robust.Shared.GameObjects.EntityEventBus.Robust.Shared.GameObjects.IDirectedEventBus.RaiseComponentEvent[TEvent](IComponent component, TEvent& args) in /home/runner/work/Delta-v-rebase/Delta-v-rebase/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 163
   at Robust.Shared.GameObjects.EntityManager.GetComponentState(IEventBus eventBus, IComponent component, ICommonSession session, GameTick fromTick) in /home/runner/work/Delta-v-rebase/Delta-v-rebase/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 1323
   at Robust.Server.GameStates.PvsSystem.GetEntityState(ICommonSession player, EntityUid entityUid, GameTick fromTick, MetaDataComponent meta) in /home/runner/work/Delta-v-rebase/Delta-v-rebase/RobustToolbox/Robust.Server/GameStates/PvsSystem.cs:line 1256
   at Robust.Server.GameStates.PvsSystem.CalculateEntityStates(IPlayerSession session, GameTick fromTick, GameTick toTick, Nullable`1[] chunks, HashSet`1 visibleChunks, EntityUid[] viewers) in /home/runner/work/Delta-v-rebase/Delta-v-rebase/RobustToolbox/Robust.Server/GameStates/PvsSystem.cs:line 700
   at Robust.Server.GameStates.ServerGameStateManager.SendStateUpdate(Int32 i, PvsThreadResources resources, InputSystem inputSystem, IPlayerSession session, Nullable`1 pvsData, UInt32& oldestAckValue) in /home/runner/work/Delta-v-rebase/Delta-v-rebase/RobustToolbox/Robust.Server/GameStates/ServerGameStateManager.cs:line 337
   at Robust.Server.GameStates.ServerGameStateManager.<>c__DisplayClass37_0.<SendStates>g__SendPlayer|0(Int32 i, ParallelLoopState state, PvsThreadResources resource) in /home/runner/work/Delta-v-rebase/Delta-v-rebase/RobustToolbox/Robust.Server/GameStates/ServerGameStateManager.cs:line 245
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

 Sawmill=resolve
 ```

**Comment by Adrian16199** [comment]
Atleast it doesnt evaporate you anymore compared to that.

**Comment by IamVelcroboy** [comment]
Was this fixed?
